# Orchis Dark Theme for Kitty

# Main colors
foreground            #e1e1e1
background            #212121
selection_foreground  #ffffff
selection_background  #3584e4

# Cursor colors
cursor                #e1e1e1
cursor_text_color     #212121

# URL underline color when hovering
url_color             #3584e4

# Kitty window border colors
active_border_color   #3584e4
inactive_border_color #2d2d2d
bell_border_color     #f66151

# Tab bar colors
active_tab_foreground   #e1e1e1
active_tab_background   #212121
inactive_tab_foreground #8d8d8d
inactive_tab_background #1e1e1e
tab_bar_background      #1e1e1e

# Terminal colors (ANSI)

# Black
color0 #212121
color8 #555555

# Red
color1 #f66151
color9 #ff7b63

# Green
color2  #57e389
color10 #62e494

# Yellow
color3  #f6d32d
color11 #ffdd33

# Blue
color4  #3584e4
color12 #62a0ea

# Magenta
color5  #c061cb
color13 #c840e9

# Cyan
color6  #2a7b88
color14 #35a8b8

# White
color7  #e1e1e1
color15 #ffffff
