id = "orchis-dark-theme"
name = "Orchis Dark Theme"
version = "0.1.0"
schema_version = 1
description = "A clean theme based off the colors of Orchis Dark"
repository = "https://github.com/owen-debiasio/orchis-dark-zed-theme"
authors = ["Owen Debiasio"]
themes = ["themes/orchis-dark.json"]
icon_themes = []
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
