# ~/.config/hypr/hyprpaper.conf

# General options
splash = true   # show the Hyprland splash on wallpapers
wallpaper_mode = fill  # default mode for all wallpapers

# Per-monitor wallpapers
wallpaper {
    monitor = DP-5
    path = /home/owen/Pictures/PXL_20260720_174931413.RAW-01.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path =  /home/owen/Pictures/PXL_20260720_174931413.RAW-01.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path =  /home/owen/Pictures/PXL_20260720_174931413.RAW-01.jpg
    fit_mode = cover
}

# Optional fallback for any monitor that doesn't match above
wallpaper {
    monitor =
    path = /home/owen/Pictures/PXL_20260720_174931413.RAW-01.jpg
    fit_mode = cover
}

