background {
    path = ~/Pictures/PXL_20260720_174931413.RAW-01.jpg
    blur_passes = 3
    blur_size = 5
    color = rgba(33, 33, 33, 1.0)
}

input-field {
    monitor = DP-1
    size = 250, 40
    position = 0, -100
    dots_size = 0.3
    dots_spacing = 0.15
    dots_center = true
    
    outer_color = rgba(53, 132, 228, 0.8)
    inner_color = rgba(33, 33, 33, 0.65)
    font_color = rgba(225, 225, 225, 1.0)
    check_color = rgba(246, 211, 45, 0.8)
    fail_color = rgba(246, 97, 81, 0.8)
    
    fade_on_empty = true
    outline_thickness = 3
}

label {
    monitor = DP-1
    text = $TIME
    font_size = 60
    color = rgba(225, 225, 225, 1.0)
    position = 0, 175
}

label {
    monitor = DP-1
    text = Welcome back, $USER
    font_size = 25
    color = rgba(225, 225, 225, 1)
    position = 0, 75
}
